export interface ReminderResponse {
  id: number;
  vehicleId: number;
  vehicleInfo?: string;
  maintenanceId?: number;
  title: string;
  description?: string;
  reminderType?: string;
  thresholdMileage?: number | null;
  thresholdDate?: string | null;
  isRecurring?: boolean;
  recurringInterval?: number;
  /** ISO del último aviso emitido por el servidor (si existe). */
  lastNotified?: string | null;
  isActive: boolean;
  /** true si viene del próximo mantenimiento guardado */
  autoGenerated?: boolean;
  createdAt?: string;
}
