class ReminderResponse {
  final int id;
  final int vehicleId;
  final String? vehicleInfo;
  final int? maintenanceId;
  final String title;
  final String? description;
  final String? reminderType;
  final int? thresholdMileage;
  final String? thresholdDate;
  final bool? isRecurring;
  final int? recurringInterval;
  final String? lastNotified;
  final bool isActive;
  final bool autoGenerated;
  final String? createdAt;

  ReminderResponse({
    required this.id,
    required this.vehicleId,
    this.vehicleInfo,
    this.maintenanceId,
    required this.title,
    this.description,
    this.reminderType,
    this.thresholdMileage,
    this.thresholdDate,
    this.isRecurring,
    this.recurringInterval,
    this.lastNotified,
    required this.isActive,
    this.autoGenerated = false,
    this.createdAt,
  });

  factory ReminderResponse.fromJson(Map<String, dynamic> json) =>
      ReminderResponse(
        id: (json['id'] as num?)?.toInt() ?? 0,
        vehicleId: (json['vehicleId'] as num?)?.toInt() ?? 0,
        vehicleInfo: json['vehicleInfo']?.toString(),
        maintenanceId: (json['maintenanceId'] as num?)?.toInt(),
        title: json['title']?.toString() ?? '',
        description: json['description']?.toString(),
        reminderType: json['reminderType']?.toString(),
        thresholdMileage: (json['thresholdMileage'] as num?)?.toInt(),
        thresholdDate: json['thresholdDate']?.toString(),
        isRecurring: json['isRecurring'] as bool?,
        recurringInterval:
            (json['recurringInterval'] as num?)?.toInt(),
        lastNotified: json['lastNotified']?.toString(),
        isActive: json['isActive'] as bool? ?? true,
        autoGenerated: json['autoGenerated'] as bool? ?? false,
        createdAt: json['createdAt']?.toString(),
      );
}
