package com.vehicle.maintenance.service;

import com.vehicle.maintenance.dto.reminder.ReminderRequest;
import com.vehicle.maintenance.dto.reminder.ReminderResponse;
import com.vehicle.maintenance.exception.ForbiddenOperationException;
import com.vehicle.maintenance.exception.ResourceNotFoundException;
import com.vehicle.maintenance.model.Reminder;
import com.vehicle.maintenance.repository.ReminderRepository;
import com.vehicle.maintenance.repository.VehicleRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class ReminderService {

    private final ReminderRepository reminderRepository;
    private final VehicleRepository vehicleRepository;

    public List<ReminderResponse> getUserReminders(Long userId) {
        return reminderRepository.findByUserIdAndIsActiveTrueOrderByCreatedAtDesc(userId)
                .stream()
                .map(this::toResponse)
                .collect(Collectors.toList());
    }

    public List<ReminderResponse> getVehicleReminders(Long vehicleId, Long userId) {
        // Verificar que el vehículo pertenece al usuario
        vehicleRepository.findByIdAndUserId(vehicleId, userId)
                .orElseThrow(() -> new ResourceNotFoundException("Vehículo", vehicleId));

        return reminderRepository.findByVehicleIdAndIsActiveTrueOrderByCreatedAtDesc(vehicleId)
                .stream()
                .map(this::toResponse)
                .collect(Collectors.toList());
    }

    public List<ReminderResponse> getDueReminders(Long userId) {
        return reminderRepository.findDueRemindersByUser(userId, LocalDate.now())
                .stream()
                .map(this::toResponse)
                .collect(Collectors.toList());
    }

    public ReminderResponse getReminderById(Long id, Long userId) {
        var reminder = reminderRepository.findByIdAndUserId(id, userId)
                .orElseThrow(() -> new ResourceNotFoundException("Recordatorio", id));
        return toResponse(reminder);
    }

    @Transactional
    public ReminderResponse createReminder(ReminderRequest request, Long userId) {
        throw new ForbiddenOperationException(
                "Los recordatorios ya no se crean a mano. Se actualizan al guardar próximos en un mantenimiento."
        );
    }

    @Transactional
    public ReminderResponse updateReminder(Long id, ReminderRequest request, Long userId) {
        throw new ForbiddenOperationException(
                "No se permite editar recordatorios a mano. Modificá el mantenimiento o la próxima fecha/km de servicio."
        );
    }

    @Transactional
    public void deleteReminder(Long id, Long userId) {
        var reminder = reminderRepository.findByIdAndUserId(id, userId)
                .orElseThrow(() -> new ResourceNotFoundException("Recordatorio", id));
        reminderRepository.delete(reminder);
    }

    @Transactional
    public void toggleReminder(Long id, Long userId) {
        var reminder = reminderRepository.findByIdAndUserId(id, userId)
                .orElseThrow(() -> new ResourceNotFoundException("Recordatorio", id));
        reminder.setIsActive(!reminder.getIsActive());
        reminderRepository.save(reminder);
    }

    private ReminderResponse toResponse(Reminder r) {
        return ReminderResponse.builder()
                .id(r.getId())
                .vehicleId(r.getVehicle().getId())
                .vehicleInfo(r.getVehicle().getBrand() + " " + r.getVehicle().getModel()
                        + " (" + r.getVehicle().getLicensePlate() + ")")
                .maintenanceId(r.getMaintenance() != null ? r.getMaintenance().getId() : null)
                .title(r.getTitle())
                .description(r.getDescription())
                .reminderType(r.getReminderType())
                .thresholdMileage(r.getThresholdMileage())
                .thresholdDate(r.getThresholdDate())
                .isRecurring(r.getIsRecurring())
                .recurringInterval(r.getRecurringInterval())
                .lastNotified(r.getLastNotified())
                .isActive(r.getIsActive())
                .autoGenerated(r.getAutoGenerated())
                .createdAt(r.getCreatedAt())
                .build();
    }
}
