package com.vehicle.maintenance.service;

import com.vehicle.maintenance.enums.ReminderType;
import com.vehicle.maintenance.model.Maintenance;
import com.vehicle.maintenance.model.Reminder;
import com.vehicle.maintenance.repository.MaintenanceRepository;
import com.vehicle.maintenance.repository.ReminderRepository;
import com.vehicle.maintenance.repository.VehicleRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.Optional;

/**
 * Actualiza el recordatorio automático por vehículo según la <strong>última</strong>
 * fila de mantenimiento por fecha de servicio: usa {@code nextServiceDate} / {@code nextServiceMileage}.
 */
@Service
@RequiredArgsConstructor
public class ReminderAutoSyncService {

    private final MaintenanceRepository maintenanceRepository;
    private final ReminderRepository reminderRepository;
    private final VehicleRepository vehicleRepository;

    @Transactional
    public void syncAutoReminderForVehicle(Long vehicleId) {
        Optional<Long> ownerIdOpt = vehicleRepository.findById(vehicleId).map(v -> v.getUser().getId());
        if (ownerIdOpt.isEmpty()) {
            return;
        }
        Long userId = ownerIdOpt.get();

        Optional<Maintenance> latestOpt = maintenanceRepository.findFirstByVehicle_IdOrderByServiceDateDescIdDesc(vehicleId);
        if (latestOpt.isEmpty()) {
            deactivateAutoReminder(vehicleId, userId);
            return;
        }

        Maintenance latest = latestOpt.get();
        LocalDate nextDate = latest.getNextServiceDate();
        Integer nextMileage = latest.getNextServiceMileage();

        if (nextDate == null && nextMileage == null) {
            deactivateAutoReminder(vehicleId, userId);
            return;
        }

        ReminderType type = resolveType(nextDate, nextMileage);
        Optional<Reminder> existing = reminderRepository.findByVehicle_IdAndUser_IdAndAutoGeneratedIsTrue(vehicleId, userId);

        String title = "Próximo servicio";
        String description = String.format(
                "Generado desde el mantenimiento «%s» (%s).",
                latest.getServiceType(),
                latest.getServiceDate()
        );

        Reminder reminder = existing.orElseGet(() -> Reminder.builder()
                .user(latest.getUser())
                .vehicle(latest.getVehicle())
                .autoGenerated(true)
                .isRecurring(false)
                .build());

        reminder.setAutoGenerated(true);
        reminder.setMaintenance(latest);
        reminder.setTitle(title);
        reminder.setDescription(description);
        reminder.setReminderType(type);
        reminder.setThresholdDate(nextDate);
        reminder.setThresholdMileage(nextMileage);
        reminder.setIsRecurring(false);
        reminder.setRecurringInterval(null);
        reminder.setIsActive(true);

        reminderRepository.save(reminder);
    }

    private static ReminderType resolveType(LocalDate nextDate, Integer nextMileage) {
        if (nextDate != null && nextMileage != null) {
            return ReminderType.BOTH;
        }
        if (nextDate != null) {
            return ReminderType.DATE_BASED;
        }
        return ReminderType.MILEAGE_BASED;
    }

    private void deactivateAutoReminder(Long vehicleId, Long userId) {
        reminderRepository.findByVehicle_IdAndUser_IdAndAutoGeneratedIsTrue(vehicleId, userId)
                .ifPresent(r -> {
                    if (Boolean.TRUE.equals(r.getIsActive())) {
                        r.setIsActive(false);
                        reminderRepository.save(r);
                    }
                });
    }
}
